---
title: "Assessment Visualisation"
output: html_document
---

```{r}
library(readr)
trees_df <- read_csv("trees.csv")
```

```{r}
# Mengecek Struktur Data
names(trees_df)
str(trees_df)
names(trees_df)[1] <- "Diameter"
trees_df$diameter_ft <- trees_df$Diameter * 0.08333
head(trees_df)
summary(trees_df)
is.na(trees_df)
```

```{r}
 # Shapiro-Wilk’s method untuk mengevaluasi normality dari setiap variable untuk mengetahui mengetahui distribusi normalnya 
shapiro.test(trees_df$diameter_ft)
shapiro.test(trees_df$Height)
shapiro.test(trees_df$Volume)
```
```{r}
# visualisasi sederhana yang menjelaskan distribusi Volume dengan menggunakan density plot 
density.default(trees_df$Volume)
```

```{r}
plot(density.default(x = trees_df$Volume))
```
```{r}
plot(density(trees_df$Volume))
```
```{r}
lm(formula = trees_df$Volume ~ trees_df$Diameter + trees_df$Height, data = trees_df)
```
```{r}
plot(lm(formula = trees_df$Volume ~ trees_df$Diameter, data = trees_df))
plot(lm(formula = trees_df$Diameter ~ trees_df$Volume, data = trees_df))
```
```{r}
plot(lm(formula = trees_df$Volume ~ trees_df$Height, data = trees_df))
```
```{r}
# mencari hubungan antara Volume batang pohon Cherry dengan diameter dan ketinggian (height)
lm(formula = Volume~Height+diameter_ft, data = trees_df)
plot(trees_df$diameter_ft, trees_df$Volume)
plot(trees_df$Height, trees_df$Volume)
```
```{r}
# uji hipotesis untuk mengetahui apakah terdapat perbedaan efek antara group 1 dan group 2 dan menganalisa efek pemberian obat tidur terhadap peningkatan lamanya waktu tidur dari sekelompok mahasiswa

library(readr) #pre-defined
library(dplyr) #pre-defined

sleep_df <- read_csv('sleep.csv') #pre-defined

# Save the data in two different dataframe/vector
group1 <- filter(sleep_df, sleep_df$group == 1)
group2 <- filter(sleep_df, sleep_df$group == 2)

# Compute t-test
t_test <- t.test(group1$extra, group2$extra)
t_test
```

```{r}
# membuat boxplot dari analisa efek pemberian obat tidur terhadap peningkatan lamanya waktu tidur dari sekelompok mahasiswa
library(ggplot2)
sleep_df
ggplot(sleep_df, aes(x=as.character(group), y = extra, fill=as.character(group))) + geom_boxplot()
```

```{r}
# model sederhana yang dapat menjelaskan bagaimana pengaruh num_people dan housearea terhadap amount_paid
library(readr)
electric_bill <- read_csv("electric_bill.csv")
model <- lm(amount_paid ~ num_people + housearea, data=electric_bill)

model
```

```{r}
# Training dan Testing dalam membuat model machine learning dengan library caret
library(readr)
library(caret)
set.seed(123)
iris <- read_csv("iris.csv")

trainIndex <- createDataPartition(iris$Species, p=0.8, list= FALSE)
training_set <- iris[trainIndex,]
testing_set <- iris[-trainIndex,]

dim(training_set)
dim(testing_set)
```

```{r}
# machine learning model dengan menggunakan Decision tree untuk memprediksi customer yang tertarik membeli mobil keluaran terbaru, serta evaluasi performance dari kedua model tersebut.

library(caret) #pre-defined 
library(rpart) #pre-defined
library(readr) #pre-defined
set.seed(123)  #pre-defined

suv_data <- read_csv("suv_data.csv") #pre-defined

#split data to training & testing set
trainIndex <- createDataPartition(suv_data$Purchased, p=0.8, list=FALSE)
training_set <- suv_data[trainIndex,]
testing_set <- suv_data[-trainIndex,]

#build model with decision tree
model_dt <- rpart(Purchased ~ ., data = training_set, method = "class")
predictions_dt <- predict(model_dt, newdata = testing_set, type = "class")

#evaluate performance with new data/ testing_set
testing_purchased <- factor(testing_set$Purchased) #pre-defined 

#show the evaluation result 
evaluation_result <- confusionMatrix(data=testing_purchased, reference=predictions_dt)
evaluation_result

```

