---
title: "Machine Learning For Retail"
output: html_document
---

```{r}
library(arules)

transaksi_tabular <- read.transactions(file="https://storage.googleapis.com/dqlab-dataset/transaksi_dqlab_retail.tsv", format="single", sep="\t", cols=c(1,2), skip=1)
write(transaksi_tabular, file="test_project_retail_1.txt", sep=",")
```

```{r}
transaksi_tabular
```

```{r}
itemsTop10 = sort(itemFrequency(transaksi_tabular, type="absolute"), decreasing = TRUE)[1:10]
transRetail = data.frame("Nama.Produk" = names(itemsTop10), "Jumlah" = itemsTop10, row.names = NULL)
transRetail
write.csv(transRetail, file="top10_item_retail.txt")
```


```{r}
itemsBottom10 <- sort(itemFrequency(transaksi_tabular, type="absolute"), decreasing=FALSE) [1:10]
transRetail = data.frame("Nama.Produk" = names(itemsBottom10), "Jumlah" = itemsBottom10, row.names = NULL)
transRetail
write.csv(transRetail, "bottom10_item_retail.txt")
```

```{r}
transaksi_rules <- apriori(transaksi_tabular, parameter=list(supp = 10 / length(transaksi_tabular), conf = 0.5, minlen = 2, maxlen = 3))
transaksi10 <- sort(transaksi_rules, by="lift", decreasing=TRUE)[1:10]
inspect(transaksi10)
write(transaksi10, "kombinasi_retail.txt")
```

```{r}
tranSM_rules <- apriori(transaksi_tabular, parameter=list(supp = 10 / length(transaksi_tabular), conf=0.1, minlen=2, maxlen=3))
tranSM_rules1 <- subset(tranSM_rules, lift > 1 & rhs %in% "Tas Makeup")
tranSM_rules2 <- subset(tranSM_rules, lift > 1 & rhs %in% "Baju Renang Pria Anak-anak")
tranSM_rules1
tranSM_rules2
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
